### PR TITLE
Validate Self Exclusion Page Inputs

### PR DESCRIPTION
**Pull request by MutatedBread**
### Scope covered
- Required fields.
- Valid numbers.
- Valid dates.
- 6 weeks after today (timeout).
- Date less then 6 months from now (exclusion).
- Date not more than 5 years (exclusion).
- Yesterday's date (timeout).
- 5 minutes before local time (timeout).
- Not more than previous set values.

### CODE REVIEW

**Review by bijan2007 — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Comment by MutatedBread** [comment]
Resolved.

**Comment by MutatedBread** [comment]
Travis built success

**Review by bijan2007 — CHANGES_REQUESTED** [review]
In SetSelfExclusion_Action you should be using assertions instead of logging for any validation or tests will always pass.

**Review by bijan2007 — APPROVED** [review]

**Pull request merged**
