### PR TITLE
Ehtesham/notify-withdraw-new

### PR DESCRIPTION
**Pull request by ehteshamy2k**
Added test for withdraw notification

### CODE REVIEW

**Review by bijan2007 — COMMENTED** [review]
@ehteshamy2k Please merge latest and resubmit PR. I've committed an important fix to master.

**Comment by ehteshamy2k** [comment]
@bijan2007 Done merging with master. Please proceed.

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007  We get this issue intermittently and this is breaking builds on Travis for this branch:

image

**Comment by ehteshamy2k** [comment]
@bijan2007 Finally, it is green. Please proceed with merge.

Thanks

**Pull request merged**
