### PR TITLE
new account creation

### PR DESCRIPTION
**Pull request by ehteshamy2k**

### CODE REVIEW

**Comment by ehteshamy2k** [comment]
@bijan2007 Could you please merge that to master.

Thanks

**Review by ridhomard — CHANGES_REQUESTED** [review]
@ehteshamy2k , Could you help to clean the PR ?its includes all the output files. Thanks

**Review by bijan2007 — COMMENTED** [review]
Can we store the new generated email in global variable or constant which can be used by other tests ?

**Comment by mohammad-deriv** [comment]
Does it create a new account on production (blue/green) every time tests being run?

**Review by binary-dmytro — CHANGES_REQUESTED** [review]
Entesham, as I can see you've implemented Account Creation autotest using API functionality. Mb it would be better to move this to a new class related to testing all the API related calls? 

I think we still need to implement autotest using a typical frontend account creation.

**Comment by ehteshamy2k** [comment]
@binary-dmytro No, I have not implemented it using API. It works from front end just like a real user. It reads token from email and then opens account.

**Comment by ehteshamy2k** [comment]
@binary-hamedanchi It creates new account on staging (blue) everytimes it runs. We can control its behavior by disabling it for staging. It can be re-enabled from xml file while testing locally on branches.

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007 I think we can store it in global variable but would that be useful? Because, all tests should be independent of each other (atomic).

Thoughts are welcome

**Comment by ehteshamy2k** [comment]
@ridhomard Sorry, I didn't get the point. Let's talk on this when you are available online.

Thanks,

**Comment by bijan2007** [comment]
@ehteshamy2k Not sure if we should run account opening for each test in staging as it will create lot of accounts.

**Comment by ashkanx** [comment]
Yes. this will add lots of accounts to database. we should find a solution for this.

**Comment by binary-dmytro** [comment]
Can't we add a custom endpoint action into the test case? We can use QA12 for the account creation, as it's our default master..Should be problems only when we rebuilding our master.
But I don't see another option considering our environments specific.

**Comment by ashkanx** [comment]
Yes. That looks the only way.

**Comment by ridhomard** [comment]
If we point to QA 12 - it mean we need to check the token inside the QA -i think it can be done if we check the token from here https://www.binaryqa12.com/emails/ - instead cloud 9

**Comment by ridhomard** [comment]
@ehteshamy2k , could you help to clean up the PR ? it has  123 files changed :/ --. Please only submit the relevant files :) - thanks

**Comment by ehteshamy2k** [comment]
creating another

**Pull request closed without merging**
