### PR TITLE
Ehtesham/browserstack-integration-new

### PR DESCRIPTION
**Pull request by ehteshamy2k**
Added browserstack integration

### CODE REVIEW

**Comment by ehteshamy2k** [comment]
@ridhomard I have removed test-output. Please review.

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007 Please review.

Thanks

**Review by bijan2007 — COMMENTED** [review]
@ehteshamy2k .classpath needs to be removed from the PR. Also I don't see the config file in the commits. ?

**Comment by ehteshamy2k** [comment]
@bijan2007 config file is added as discussed

**Review by bijan2007 — COMMENTED** [review]
@ehteshamy2k We cannot keep BS key openly in a file as it will raise security concerns. Please remove it and find a way to encrypt it or pass in some secured manner.

**Comment by ehteshamy2k** [comment]
@bijan2007 Mostly we would be running browserstack tests locally on our machines so we can omit the keys altogether from config file. The one who has to use it should fetch it from lastpass.com

@ashkanx could you suggest on this please?

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007 I have scratched Browserstack key from config file so you can safely merge it.

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007 This branch now has two important fixes aside from browserstack integration
1. Fix for Chrome60 and TravisCI issue
2. Fix for Mailinator as Mailinator has updated their layout.

Tests are failing intermittently without any pattern

Thanks

**Comment by ehteshamy2k** [comment]
@bijan2007 Build is successful finally. Could you please proceed and merge it?

Thanks

**Pull request merged**
