### PR TITLE
Ehtesham/browserstack

### PR DESCRIPTION
**Pull request by ehteshamy2k**
Added support to run tests on browserstack.com

### CODE REVIEW

**Comment by ridhomard** [comment]
@ehteshamy2k , can you clean up the PR , please don't include test-output. ? such as : t_est-output/..._

It will be more easy to review and clean :) - Thanks

**Review by ridhomard — CHANGES_REQUESTED** [review]
Pls remove test-output from PR

**Comment by ehteshamy2k** [comment]
Sure @ridhomard

**Comment by ehteshamy2k** [comment]
Closing PR to recreate it after cleaning

**Pull request closed without merging**
